refactor(instr-knex): use exported strings for attributes
open-telemetry/opentelemetry-js-contrib pull request #2109
Opened 2024-04-17 15:28 UTC by david-luna

## Which problem is this PR solving?

- Updates #2025 

## Short description of the changes

- Update @opentelemetry/semantic-conventions to ^1.22
- Replace `SemanticAttributes.*` with exported strings `SEMATTRS_*`
- Update README with new semantic convention package version and key

2024-04-17 15:43 UTC, pichlermarc requested changes
This one looks like it's missing the update to `package.json` and `package-lock.json` :slightly_smiling_face:

2024-04-17 16:11 UTC, david-luna commented
> This one looks like it's missing the update to `package.json` and `package-lock.json` 🙂

Indeed! thanks for the heads up :)

2024-04-17 18:52 UTC, trentm approved these changes

2024-04-18 11:20 UTC, pichlermarc approved these changes

2024-04-18 11:21 UTC, merged