chore: 0.15.0 release proposal
open-telemetry/opentelemetry-js-contrib pull request #401
Opened 2021-03-31 15:22 UTC by dyladan

#### :rocket: Enhancement
* Other
  * [#366](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/366) Add automated release workflows ([@willarmiros](https://github.com/willarmiros))
  * [#391](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/391) chore: adding meta package for web ([@obecny](https://github.com/obecny))
  * [#393](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/393) feat: mysql instrumentation ([@dyladan](https://github.com/dyladan))
  * [#327](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/327) feat: enable root span to contain route ([@DinaYakovlev](https://github.com/DinaYakovlev))
  * [#389](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/389) feat: net module instrumentation ([@seemk](https://github.com/seemk))
  * [#379](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/379) chore: creating meta package for default auto instrumentations for node ([@obecny](https://github.com/obecny))
  * [#380](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/380) Moving Hapi Plugin to Instrumentation ([@obecny](https://github.com/obecny))
* `opentelemetry-host-metrics`
  * [#395](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/395) chore: fixing broken links, updating to correct base url, replacing gitter with github discussions ([@obecny](https://github.com/obecny))

#### :house: Internal
* [#392](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/392) chore: fixing broken links ([@obecny](https://github.com/obecny))

#### :memo: Documentation
* `opentelemetry-host-metrics`
  * [#373](https://github.com/open-telemetry/opentelemetry-js-contrib/pull/373) Update README.md ([@z1c0](https://github.com/z1c0))

#### Committers: 7
- Bartlomiej Obecny ([@obecny](https://github.com/obecny))
- Daniel Dyla ([@dyladan](https://github.com/dyladan))
- Dina.Yakovlev ([@DinaYakovlev](https://github.com/DinaYakovlev))
- Siim Kallas ([@seemk](https://github.com/seemk))
- Valentin Marchaud ([@vmarchaud](https://github.com/vmarchaud))
- William Armiros ([@willarmiros](https://github.com/willarmiros))
- Wolfgang Ziegler ([@z1c0](https://github.com/z1c0))

2021-03-31 15:34 UTC, vmarchaud approved these changes

2021-03-31 18:14 UTC, Flarna commented on plugins/node/opentelemetry-instrumentation-pg/package.json
> +    "@opentelemetry/test-utils": "^0.15.0",
same here

2021-03-31 18:15 UTC, Flarna commented on plugins/node/opentelemetry-plugin-mysql/package.json
> +    "@opentelemetry/test-utils": "^0.15.0",
once again

2021-03-31 18:15 UTC, Flarna approved these changes

2021-03-31 18:19 UTC, Flarna commented on plugins/node/opentelemetry-instrumentation-mysql/package.json
> +    "@opentelemetry/test-utils": "^0.15.0",
Actually I don't care that much, just noticed during scanning the files. Feel free to let the bots do the work.

2021-04-01 12:10 UTC, dyladan commented
> Regarding the compile problem you have here. I think it's caused by the transitive dependency to `@hapi/podium` from `@hapi/hapi`. Version 4.1.2 was released recently. If you add `"@hapi/podium": "4.1.1"` in package.json problem should be gone.
> 
> Maybe updating all dependencies to latests solves the problem also.

Thanks. There is also a problem with the transitive dependencies hinted in https://github.com/open-telemetry/opentelemetry-js/issues/2065. The build fails because one of our dependencies (web) depends on another (tracing) with a `^` range. We also depend on a pinned version of `tracing`. This means tracing is installed twice with nesting in node_modules and typescript fails to install it. Fixing this requires merging the above PR.

2021-04-01 15:20 UTC, jtmalinowski requested changes
It will publish `propagator-jaeger@0.15.0`, even though it was already published `@0.18.2`. If we resolve the Hapi issue I can rebase https://github.com/open-telemetry/opentelemetry-js-contrib/pull/351 and we'll be good to merge it before publishing this release.

2021-04-01 15:59 UTC, dyladan commented
> Regarding the compile problem you have here. I think it's caused by the transitive dependency to `@hapi/podium` from `@hapi/hapi`. Version 4.1.2 was released recently. If you add `"@hapi/podium": "4.1.1"` in package.json problem should be gone.
> 
> Maybe updating all dependencies to latests solves the problem also.

Your suggested fix doesn't work for me at least locally. Skipping lib checks in the tsconfig does, but that feels somehow wrong to me.

2021-04-01 16:04 UTC, vmarchaud commented
> Skipping lib checks in the tsconfig does, but that feels somehow wrong to me.

We could only skip it for Hapi, sadly it sometimes happen and generally requires upstream dependencies to fix their types which can take some time. In our case that shouldn't impact too much i believe

2021-04-01 16:34 UTC, Flarna commented
> Your suggested fix doesn't work for me at least locally

That's strange as I tried it locally and it worked for me.

2021-04-01 16:44 UTC, dyladan commented
> > Your suggested fix doesn't work for me at least locally
> 
> That's strange as I tried it locally and it worked for me.

Can you send me the exact package.json? Or open a PR?

2021-04-01 16:44 UTC, Flarna commented
Created https://github.com/open-telemetry/opentelemetry-js-contrib/pull/407 - let the CI decide

2021-04-01 20:37 UTC, dyladan commented
Closing in favor of the bot version #409

2021-04-01 20:37 UTC, closed without merging