feat: move aws/gcp detectors from opentelemetry-js repo
open-telemetry/opentelemetry-js-contrib pull request #593
Opened 2021-07-28 07:16 UTC by legendecas

## Which problem is this PR solving?

Fixes https://github.com/open-telemetry/opentelemetry-js/issues/1689

## Short description of the changes
 
- move aws/gcp detectors from optentelemetry-js repo
- migrate @opentelemetry/resources/test/util/resource-assertions.ts to local private project @opentelemetry/test-utils.

2021-07-28 17:31 UTC, Flarna commented on detectors/node/opentelemetry-resource-detector-gcp/package.json
> +  "repository": "open-telemetry/opentelemetry-js",
```suggestion
  "repository": "open-telemetry/opentelemetry-js-contrib",
```

2021-07-28 17:31 UTC, Flarna commented on detectors/node/opentelemetry-resource-detector-aws/package.json
> +  "repository": "open-telemetry/opentelemetry-js",
```suggestion
  "repository": "open-telemetry/opentelemetry-js-contrib",
```

2021-07-28 17:32 UTC, Flarna commented on detectors/node/opentelemetry-resource-detector-aws/README.md
> +[dependencies-url]: https://david-dm.org/open-telemetry/opentelemetry-js?path=packages%2Fopentelemetry-resources
I guess some urls need to be updated here and in gcp readme

2021-07-28 17:33 UTC, Flarna requested changes
Just minor nits.

But i set it to need work to block merging until contrib 0.24.0 is out as these packages have been released already via core repo in version 0.24.0

2021-07-28 17:34 UTC, Flarna commented on detectors/node/opentelemetry-resource-detector-aws/package.json
> +  "version": "0.23.0",
```suggestion
  "version": "0.24.0",
```
it will be 0.24.0 (or later) at the timer of merge.

2021-07-30 05:16 UTC, legendecas commented
@Flarna thanks for reviews. Updated, PTAL again :)

2021-07-30 10:36 UTC, Flarna approved these changes

2021-07-30 10:36 UTC, Flarna commented on detectors/node/opentelemetry-resource-detector-aws/package.json
> +    "node": ">=8.0.0"
```suggestion
    "node": ">=8.5.0"
```

2021-08-03 11:11 UTC, Rauno56 approved these changes

2021-08-03 11:12 UTC, Rauno56 commented
This also requires a companion-PR to remove the code from `opentelemetry-js`.

2021-08-03 18:52 UTC, obecny commented
is there an easy way to make diff this vs https://github.com/open-telemetry/opentelemetry-js/pull/2392 ?

2021-08-04 04:23 UTC, legendecas commented
@obecny suppose we have those two repo in a root directory, and opentelemetry-js is on main branch, we can use `diff`

```
> diff --exclude package-lock.json \
  opentelemetry-js/packages/opentelemetry-resource-detector-aws/ \
  opentelemetry-js-contrib/detectors/node/opentelemetry-resource-detector-aws/
```

2021-08-04 17:21 UTC, obecny approved these changes
lgtm

2021-08-04 17:22 UTC, merged