feat(add-tav-action): add test-all-versions as github action
open-telemetry/opentelemetry-js-contrib pull request #778
Opened 2021-12-07 15:47 UTC by haddasbronfman

## Which problem is this PR solving?

- This PR is solving this issue: https://github.com/open-telemetry/opentelemetry-js-contrib/issues/756

## Short description of the changes

-I added a new github action, which is using dorny/paths-filter to get all the changes packages, and for each such package, run the command "npm run test-all-versions" - if it exist.

2021-12-08 15:01 UTC, dyladan commented
it seems like you're filtering only the packages which have changed using some other action? Why not use the built-in lerna filtering functionality?

2021-12-08 15:51 UTC, dyladan commented
Looks like the check fails

2021-12-09 15:40 UTC, dyladan reviewed
It looks like you don't install dependencies or build the packages. Are you sure it will work? Can you please make a small change to a package with a test-all-versions script so we can verify that it runs properly? Modifying the readme slightly should be enough.

2021-12-09 15:40 UTC, dyladan commented on .github/workflows/test-all-versions.yml
> +      - run: lerna run test-all-versions --since origin/main
nit
```suggestion
      - run: lerna run test-all-versions --since origin/main

```

2021-12-09 16:00 UTC, dyladan commented
you need to install dependencies and build the project. You can see how this is done in the unit test workflow but usually you have to do `npm install --ignore-scripts`, then `lerna bootstrap --since origin/main --include-dependencies`, then `lerna run compile --since origin/main --include-dependencies`. Then you should be able to do the test all versions script.

2021-12-09 21:27 UTC, dyladan commented
the `feat` identifier in the title signifies the minor version number to be incremented in our release automation. Please use a more appropriate conventional commits identifier like `test`

2021-12-09 21:42 UTC, dyladan commented
I'm not sure why it says mongo isn't started. @Rauno56 is there some additional needed step for the tav script?

2021-12-10 09:18 UTC, Rauno56 commented
Some tests need an service to be running in order to work: see "services" in [unit-test.yml](./.github/workflows/unit-test.yml).

2021-12-15 16:19 UTC, blumamir commented
Thanks for adding this.
The current action will run only against packages that had changes in each PR.
This will do a good job of catching errors with old versions that are introduced in the current PR.

Instrumentations are patching the internal logic of packages that are out of our control. It means that if the original instrumented library author published a new version to npm which breaks something in the instrumentation, no automatic process will catch that until someone makes a change to the instrumentation packages, or when a user complains (probably after something breaks in his deployment due to the OTEL installation).

This had happened before with `aws-sdk`, which has a complex internal logic and tends to publish new versions often.

At the [opentelemetry-ext-js project](https://github.com/aspecto-io/opentelemetry-ext-js) we run test-all-versions on all packages every day with [github actions scheduled-events](https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#scheduled-events), so if someone pushes a new version to npm which is not compatible with the current instrumentation, we get notified (in slack) after at most 24 hours.
Github action configuration for reference: https://github.com/aspecto-io/opentelemetry-ext-js/blob/master/.github/workflows/daily-test.yml
sidenote: the daily tests currently fails due to kafkajs, we need to look at it and fix it

2021-12-15 16:32 UTC, vmarchaud commented
> At the opentelemetry-ext-js project we run test-all-versions on all packages every day with github actions scheduled-events, so if someone pushes a new version to npm which is not compatible with the current instrumentation, we get notified (in slack) after at most 24 hours.

We could do both but i worry it may require too much bandwith to fix them when alert comes off (i guess it depend of component maintainers) resulting in maintainer generally ignoring errors

2021-12-15 16:33 UTC, dyladan commented
> > At the opentelemetry-ext-js project we run test-all-versions on all packages every day with github actions scheduled-events, so if someone pushes a new version to npm which is not compatible with the current instrumentation, we get notified (in slack) after at most 24 hours.
> 
> We could do both but i worry it may require too much bandwith to fix them when alert comes off (i guess it depend of component maintainers) resulting in maintainer generally ignoring errors

I think not knowing about errors is a worse outcome than having errors that go unfixed for a while. I think this comes down to trusting the component authors and giving them a chance to succeed first before assuming they will fail.

2021-12-15 20:21 UTC, vmarchaud commented
Lets go both then ?

2021-12-26 14:24 UTC, vmarchaud approved these changes

2021-12-27 15:12 UTC, dyladan approved these changes

2021-12-27 15:12 UTC, dyladan commented on .github/workflows/test-all-versions.yml
> +      - run: lerna run test-all-versions --since origin/main --stream --concurrency=1
nit:
```suggestion
      - run: lerna run test-all-versions --since origin/main --stream --concurrency=1

```

2021-12-27 19:23 UTC, vmarchaud requested changes
waiting for the cron scheduled workflow to be added before approving, otherwise seems good

2021-12-27 19:45 UTC, dyladan commented
@vmarchaud this particular action runs only the changed packages on pull requests. I think the full all-package cron can be done in a follow-up PR. @haddasbronfman do you agree?

2021-12-27 21:22 UTC, vmarchaud commented
> @haddasbronfman do you agree?

We discussed this privately on slack, i suggested to make only one for both (since it's closely related) but if you believe its bettter to make two i don't mind

2021-12-27 21:22 UTC, vmarchaud approved these changes

2021-12-27 21:23 UTC, dyladan commented
> > @haddasbronfman do you agree?
> 
> We discussed this privately on slack, i suggested to make only one for both (since it's closely related) but if you believe its bettter to make two i don't mind

No I just didn't realize you had already discussed this. Go ahead with whatever you already decided.

2021-12-28 09:50 UTC, vmarchaud commented
@haddasbronfman As you prefer then :)

2021-12-29 06:37 UTC, haddasbronfman commented
Hi,
I prefer to do it on another PR is this is ok with you.

2021-12-29 10:41 UTC, merged